---
# defaults file for kubeadm_install
k8s:
  kernel:
    modules:
      - overlay
      - br_netfilter

  release_url: https://dl.k8s.io/release/stable.txt

  kubelet:
    version: v0.8.0
    url: "https://raw.githubusercontent.com/kubernetes/release/"
    folder: /etc/systemd/system/

  kubeadm:
    version: v0.8.0
    url: "https://raw.githubusercontent.com/kubernetes/release/"
    folder: /etc/systemd/system/kubelet.service.d/

  cni:
    folder: /opt/cni/bin
    version: v0.9.1
    url: https://github.com/containernetworking/plugins/releases/download/
  cri:
    folder: /usr/local/bin
    version: v1.21.0
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/

  files:
    module_load: /etc/modules-load.d/k8s.conf
    sysctl_bridge: /etc/sysctl.d/k8s.conf
    
  network_config:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.ipv4.ip_forward                 = 1
     
containerd:
  enabled: True
  version: 1.4.4
  files:
    module_load: /etc/modules-load.d/containerd.conf
    sysctl_bridge: /etc/sysctl.d/99-kubernetes-cri.conf

package:
  enabled: True

hostname:
  name: testserver
  enabled: False