---
- name: Install Kube tools Link
  block:
    - name: Connect to website using a previously stored cookie
      uri:
        url: "{{ k8s.release_url }}"
        method: GET
        return_content: yes
      register: k8s_release

    - name: K8s Version
      debug:
        msg: "{{ k8s_release.content  }}"

    - name: Get Kube -> adm, let and ctl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_release.content }}/bin/linux/amd64/{{ item }}"
        dest: /usr/bin/
        mode: u+x
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Create Kubeadm Conf directory
      ansible.builtin.file:
        path: "{{ k8s.kubeadm.folder }}"
        state: directory
        mode: 0644

    - name: Get Kube -> adm, let and ctl
      get_url:
        url: "{{ k8s.kubeadm.url }}{{ k8s.kubeadm.version }}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf"
        dest: "{{ k8s.kubeadm.folder }}"
        mode: 0644 

    - name: Connect to website using a previously stored cookie
      get_url:
        url: "{{ k8s.kubelet.url }}{{ k8s.kubelet.version }}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service"
        dest: "{{ k8s.kubelet.folder }}"
        mode: 0644
  when: not package.enabled

- name: Install Kube tools Link
  block:
    - name: Add keys k8s
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Install k8s Modules
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install k8s packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl
  when: package.enabled